# Generated by Django 3.0.8 on 2021-01-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Detection', '0003_userform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='emp_id',
            new_name='face_id',
        ),
    ]
